### ISSUE TITLE
Memory access fault by GPU node-4 after using hipfftExecR2C

### ISSUE THREAD

**Issue by holyprince** [ROCmSoftwarePlatform/rocFFT#211]
I have ported a program to hip. It is an iteration framework and in each iteration, it will use hipfftExecR2C many times. However, there is a strange bug is that I will randomly get the memory out error after 3 or more iterations like this :

`
Memory access fault by GPU node-4 (Agent handle: 0x2a9e950) on address 0x2b118b909000. Reason: Page not present or supervisor privilege.
`

Although the break down is random, every time the bug appeared after using hipfftExecR2C transform and invoke the hipMemcpy to copy the hipFloatComplex data and the error is as folows:

```
#25 0x00002aaab320f7e5 in copy_ext () at /data/my-tests/others/hcc-roc-2.1.x/lib/hsa/mcwamp_hsa.cpp:4131
#26 0x00002aaaabbddc48 in ihipStream_t::locked_copySync(void*, void const*, unsigned long, unsigned int, bool) ()
   from /opt/rocm/hip/lib/libhip_hcc.so
#27 0x00002aaaabc9879e in hipMemcpy () from /opt/rocm/hip/lib/libhip_hcc.so
#28 0x00000000005271c9 in getFourierTransformsAndCtfs<MlOptimiserHip> (my_ori_particle=0, op=..., sp=..., baseMLO=0x7fffffffb038,
    accMLO=0x14a9ed0, ptrFactory=..., ibody=0) at src/acc/hip/../acc_ml_optimiser_impl.h:492

```

Sorry to disturbed and I want to find some tips to solve this probelm, Thank you very much !

| Software | version |
|-----|-----|
| rocFFT | v0.9.4 |
| rocm | v2.1 |

and I add the full track :
```
#0  0x00002aaab08b2107 in ioctl () from /lib64/libc.so.6
#1  0x00002aaab0b91ad8 in ?? () from /opt/rocm/lib64/libhsakmt.so.1
#2  0x00002aaab0b8aa3e in hsaKmtWaitOnMultipleEvents () from /opt/rocm/lib64/libhsakmt.so.1
#3  0x00002aaab0b8b059 in hsaKmtWaitOnEvent () from /opt/rocm/lib64/libhsakmt.so.1
#4  0x00002aaaac5005b2 in ?? () from /opt/rocm/hsa/lib/libhsa-runtime64.so.1
#5  0x00002aaaac50040a in ?? () from /opt/rocm/hsa/lib/libhsa-runtime64.so.1
#6  0x00002aaaac4f2ad9 in ?? () from /opt/rocm/hsa/lib/libhsa-runtime64.so.1
#7  0x00002aaab323a2b4 in waitComplete () at /data/my-tests/others/hcc-roc-2.1.x/lib/hsa/mcwamp_hsa.cpp:4884
#8  0x00002aaab324039d in operator() () at /data/my-tests/others/hcc-roc-2.1.x/lib/hsa/mcwamp_hsa.cpp:5015
#9  __invoke_impl<void, (lambda at /data/my-tests/others/hcc-roc-2.1.x/lib/hsa/mcwamp_hsa.cpp:5014:77)> ()
    at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/invoke.h:60
#10 __invoke<(lambda at /data/my-tests/others/hcc-roc-2.1.x/lib/hsa/mcwamp_hsa.cpp:5014:77)> ()
    at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/invoke.h:95
#11 _M_invoke<0> () at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/thread:234
#12 operator() () at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/thread:243
#13 operator() () at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/future:1362
#14 0x00002aaab3240332 in _M_invoke ()
    at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/std_function.h:301
#15 0x00002aaab3231607 in operator() ()
    at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/bits/std_function.h:706
#16 _M_do_set () at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/future:561
#17 0x00002aaaab4e9e20 in pthread_once () from /lib64/libpthread.so.0
#18 0x00002aaab3240763 in __gthread_once ()
    at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/x86_64-redhat-linux/bits/gthr-default.h:699
#19 call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()> *, bool *), std::__future_base::_State_baseV2 *, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()> *, bool *> ()
    at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/mutex:684
#20 _M_set_result () at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/future:401
#21 _M_complete_async () at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/future:1615
#22 0x00002aaab320df74 in wait ()
    at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/future:334
#23 wait () at /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/future:692
#24 wait () at /data/my-tests/others/hcc-roc-2.1.x/lib/hsa/mcwamp_hsa.cpp:1617
#25 0x00002aaab320f7e5 in copy_ext () at /data/my-tests/others/hcc-roc-2.1.x/lib/hsa/mcwamp_hsa.cpp:4131
#26 0x00002aaaabbddc48 in ihipStream_t::locked_copySync(void*, void const*, unsigned long, unsigned int, bool) ()
   from /opt/rocm/hip/lib/libhip_hcc.so
#27 0x00002aaaabc9879e in hipMemcpy () from /opt/rocm/hip/lib/libhip_hcc.so
#28 0x00000000005271c9 in getFourierTransformsAndCtfs<MlOptimiserHip> (my_ori_particle=0, op=..., sp=..., baseMLO=0x7fffffffb038,
    accMLO=0x14a9ed0, ptrFactory=..., ibody=0) at src/acc/hip/../acc_ml_optimiser_impl.h:492
#29 0x00000000004ef0dc in accDoExpectationOneParticle<MlOptimiserHip> (myInstance=0x14a9ed0, my_ori_particle=0, thread_id=0,
    ptrFactory=...) at src/acc/hip/../acc_ml_optimiser_impl.h:3185
#30 0x00000000004eeb70 in MlOptimiserHip::doThreadExpectationSomeParticles (this=0x14a9ed0, thread_id=0) at src/acc/hip/hip_ml_optimiser.hip.cpp:284
#31 0x00000000008cf123 in globalThreadExpectationSomeParticles (thArg=...) at ./src/ml_optimiser.cpp:76
#32 0x00000000009e3a78 in _threadMain (data=0x14618a0) at ./src/parallel.cpp:129
#33 0x00002aaaab4e4e25 in start_thread () from /lib64/libpthread.so.0
#34 0x00002aaab08bb34d in clone () from /lib64/libc.so.6

```

**Comment by malcolmroberts** [comment]
Well, if it's a memory fault, it's hard to tell exactly what's happening without more information.  Could you provide a minimal working example?

**Comment by holyprince** [comment]
Now I can not use a simple demo to reproduce the bug, but before I use 2 mpi threads on one GPU, the bug will appear but when I use 2 mpi threads on two GPU, the bug disappears.
I am not sure this information whether can help to find the possible reason.

**Comment by malcolmroberts** [comment]
This has been quiet for a while; if you've managed to solve this issue by local code changes, or perhaps by upgrading rocFFT and/or the rest of your stack, we could perhaps close this issue.
