### ISSUE TITLE
Samples fail ROCm 2.8, GFX7, FX CPU.

### ISSUE THREAD

**Issue by Lucretia** [ROCmSoftwarePlatform/rocFFT#267]
### What is the expected behavior
-  Unknown

### What actually happens
- Exception raised, GDB session:

```
r
Starting program: /tmp/staging/fixed-16-double 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffea98e700 (LWP 31174)]
terminate called after throwing an instance of 'std::runtime_error'
  what():  Undefined __global__ function.

Thread 1 "fixed-16-double" received signal SIGABRT, Aborted.
0x00007ffff7189a01 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff7189a01 in raise () from /lib64/libc.so.6
#1  0x00007ffff7173535 in abort () from /lib64/libc.so.6
#2  0x00007ffff73d7703 in __gnu_cxx::__verbose_terminate_handler () at /var/tmp/portage/sys-devel/gcc-9.2.0-r1/work/gcc-9.2.0/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff7407796 in __cxxabiv1::__terminate (handler=<optimized out>) at /var/tmp/portage/sys-devel/gcc-9.2.0-r1/work/gcc-9.2.0/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007ffff74077e1 in std::terminate () at /var/tmp/portage/sys-devel/gcc-9.2.0-r1/work/gcc-9.2.0/libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00007ffff7407a13 in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x7ffff759c0f8 <typeinfo for std::runtime_error>, dest=0x7ffff741d420 <std::runtime_error::~runtime_error()>)
    at /var/tmp/portage/sys-devel/gcc-9.2.0-r1/work/gcc-9.2.0/libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0x00007ffff75e55cd in hip_impl::hip_throw (ex=...) at /var/tmp/portage/sys-devel/hip-2.8.0/work/HIP-roc-2.8.0/src/hip_hcc.cpp:2507
#7  0x00007ffff75c2ff7 in hip_impl::program_state_impl::kernargs_size_align (this=0x45ca50, kernel=140737293554832) at /var/tmp/portage/sys-devel/hip-2.8.0/work/HIP-roc-2.8.0/src/program_state.inl:816
#8  0x00007ffff75c2c79 in hip_impl::program_state::get_kernargs_size_align (this=<optimized out>, kernel=140737488342368) at /var/tmp/portage/sys-devel/hip-2.8.0/work/HIP-roc-2.8.0/src/program_state.cpp:82
#9  0x00007ffff4641431 in hip_impl::make_kernarg<HIP_vector_type<double, 2u> const*, unsigned long, unsigned long const*, unsigned long const*, unsigned long, HIP_vector_type<double, 2u>*, HIP_vector_type<double, 2u> const*, unsigned long, unsigned long const*, unsigned long const*, unsigned long, HIP_vector_type<double, 2u>*> (kernel=
    0x7ffff4639490 <fft_fwd_ip_len16<HIP_vector_type<double, 2u>, (StrideBin)0>(HIP_vector_type<double, 2u> const*, unsigned long, unsigned long const*, unsigned long const*, unsigned long, HIP_vector_type<double, 2u>*)>, actuals=...)
    at /usr/lib/hip/include/hip/hcc_detail/functional_grid_launch.hpp:102
#10 0x00007ffff46393df in hipLaunchKernelGGL<HIP_vector_type<double, 2u> const*, unsigned long, unsigned long const*, unsigned long const*, unsigned long, HIP_vector_type<double, 2u>*, void (*)(HIP_vector_type<double, 2u> const*, unsigned long, unsigned long const*, unsigned long const*, unsigned long, HIP_vector_type<double, 2u>*)> (kernel=0x7fffffffcd60, numBlocks=..., dimBlocks=..., sharedMemBytes=0, stream=<optimized out>, args=<optimized out>, args=<optimized out>, 
    args=<optimized out>, args=<optimized out>, args=<optimized out>, args=<optimized out>) at /usr/lib/hip/include/hip/hcc_detail/functional_grid_launch.hpp:165
#11 rocfft_internal_dfn_dp_ci_ci_stoc_16 (data_p=<optimized out>, back_p=<optimized out>) at library/src/device/kernel_launch_double_0.cpp.h:28
#12 0x00007ffff7f2efc5 in TransformPowX (execPlan=..., in_buffer=0x7fffffffd3b8, out_buffer=0x7fffffffd3b8, info=0x0) at /usr/src/debug/sci-libs/rocFFT-2.8.0/rocFFT-rocm-2.8/library/src/powX.cpp:319
#13 0x00007ffff7f2896d in rocfft_execute (plan=0x0, in_buffer=0x7fffffffcd60, out_buffer=<optimized out>, info=0x7ffff7189a01 <raise+321>) at /usr/src/debug/sci-libs/rocFFT-2.8.0/rocFFT-rocm-2.8/library/src/transform.cpp:94
#14 0x0000000000401428 in main () at /var/tmp/portage/sci-libs/rocFFT-2.8.0/work/rocFFT-rocm-2.8/clients/samples/fixed-16/fixed-16-double.cpp:82
```

### How to reproduce
-  Just run on older hardware

### Environment
| Hardware | description |
|-----|-----|
| GPU | Hawaii PRO [Radeon R9 290/390] |
| CPU | AMD FX(tm)-8350 Eight-Core Processor |

| Software | version |
|-----|-----|
| ROCK | v2.8 |
| ROCR | v2.8 |
| HCC | v2.8 |
| Library | v2.8 |

I don't know if this is meant to work at all, but each of the samples fail with the same message.

I'm just experimenting with this to see if my machine can get it all to work.

**Comment by malcolmroberts** [comment]
Are you able to run simple kernels on your setup?

**Comment by Lucretia** [comment]
I've not tried, is there some simple example I can try?

**Comment by malcolmroberts** [comment]
Here's a simple example to try out:

```
// Compile with hipcc
#include <hip/hip_runtime.h>
#include <iostream>
__global__ void mykernel(float* a)
{
    a[0] = 1.0;
}

int main()
{
    float*  d_p     = NULL;
    hipMalloc(&d_p, sizeof(float));
    hipError_t rt = hipSuccess;
    hipLaunchKernelGGL(mykernel,
                       dim3(1),
                       dim3(1),
                       0, // sharedMemBytes
                       0, // stream
                       d_p);
    float hostfloat;
    hipMemcpy(&hostfloat, d_p, sizeof(float), hipMemcpyDeviceToHost);
    std::cout << hostfloat << std::endl;
    assert(hipFree(d_p) == hipSuccess);
    return 0;
}
```
I'm also going to double-check support for your card.

**Comment by Lucretia** [comment]
Seems I can. Tried, [these](https://rocm.github.io/QuickStartOCL.html), all worked until Exercise06/C which says:

```
$ ./mult 

Using OpenCL device: gfx701

===== Sequential, matrix mult (dot prod), order 1024 on host CPU ======
 9.27 seconds at 231.6 MFLOPS 

===== OpenCL, matrix mult, C(i,j) per work item, order 1024 ======
 0.00 seconds at 12485370.0 MFLOPS 

 Errors in multiplication: 247390116249600.000000
```

**Comment by Lucretia** [comment]
> Here's a simple example to try out:
> 
> ```
> // Compile with hipcc
> #include <hip/hip_runtime.h>
> #include <iostream>
> __global__ void mykernel(float* a)
> {
>     a[0] = 1.0;
> }
> 
> int main()
> {
>     float*  d_p     = NULL;
>     hipMalloc(&d_p, sizeof(float));
>     hipError_t rt = hipSuccess;
>     hipLaunchKernelGGL(mykernel,
>                        dim3(1),
>                        dim3(1),
>                        0, // sharedMemBytes
>                        0, // stream
>                        d_p);
>     float hostfloat;
>     hipMemcpy(&hostfloat, d_p, sizeof(float), hipMemcpyDeviceToHost);
>     std::cout << hostfloat << std::endl;
>     assert(hipFree(d_p) == hipSuccess);
>     return 0;
> }
> ```
> 
> I'm also going to double-check support for your card.

That example ran and output "1" so, seems to work.

**Comment by malcolmroberts** [comment]
Are you able to run the rocFFT examples without gdb?

**Comment by Lucretia** [comment]
No, they give the same error.

```
$ ./fixed-16-double 
terminate called after throwing an instance of 'std::runtime_error'
  what():  Undefined __global__ function.
Aborted
$ ./fixed-16-float
terminate called after throwing an instance of 'std::runtime_error'
  what():  Undefined __global__ function.
Aborted
$ ./fixed-16-float-hipfft
hipFFT version 906
terminate called after throwing an instance of 'std::runtime_error'
  what():  Undefined __global__ function.
Aborted
$ ./fixed-large-double
size of workbuffer=2097152
terminate called after throwing an instance of 'std::runtime_error'
  what():  Undefined __global__ function.
Aborted
$ ./fixed-large-float
size of workbuffer=1048576
terminate called after throwing an instance of 'std::runtime_error'
  what():  Undefined __global__ function.
Aborted
$ ./hipfft_1d_d2z
hipfft 1D double-precision real-to-complex transform
terminate called after throwing an instance of 'std::runtime_error'
  what():  Missing metadata for __global__ function: _Z8initdataPdi
Aborted
$ ./hipfft_1d_z2z
hipfft 1D double-precision complex-to-complex transform
terminate called after throwing an instance of 'std::runtime_error'
  what():  Missing metadata for __global__ function: _Z8initdataP15HIP_vector_typeIdLj2EEi
Aborted
$ ./hipfft_2d_d2z
hipfft 2D double-precision real-to-complex transform
Nx: 4   Ny 5
terminate called after throwing an instance of 'std::runtime_error'
  what():  Missing metadata for __global__ function: _Z8initdataPdmmm
Aborted
$ ./hipfft_2d_z2z
hipfft 2D double-precision complex-to-complex transform
terminate called after throwing an instance of 'std::runtime_error'
  what():  Missing metadata for __global__ function: _Z8initdataP15HIP_vector_typeIdLj2EEii
Aborted
$ ./hipfft_3d_d2z
hipfft 3D double-precision real-to-complex transform
Nx: 4   Ny 5    Nz 6
terminate called after throwing an instance of 'std::runtime_error'
  what():  Missing metadata for __global__ function: _Z8initdataPdmmmm
Aborted
$ ./hipfft_3d_z2z
hipfft 3D double-precision complex-to-complex transform
terminate called after throwing an instance of 'std::runtime_error'
  what():  Missing metadata for __global__ function: _Z8initdataP15HIP_vector_typeIdLj2EEiii
Aborted
$ ./hipfft_planmany_2d_r2c
hipfft 2D single-precision real-to-complex transform using advanced interface
n: 4 5
howmany: 3
istride: 1      ostride: 1
inembed: 4 6
onembed: 4 3
idist: 24       odist: 12

input:
batch: 0
0 1 2 3 4 0 
1 2 3 4 5 0 
2 3 4 5 6 0 
3 4 5 6 7 0 

batch: 1
1 2 3 4 5 0 
2 3 4 5 6 0 
3 4 5 6 7 0 
4 5 6 7 8 0 

batch: 2
2 3 4 5 6 0 
3 4 5 6 7 0 
4 5 6 7 8 0 
5 6 7 8 9 0 


terminate called after throwing an instance of 'std::runtime_error'
  what():  Undefined __global__ function.
Aborted
$ ./hipfft_planmany_2d_z2z
hipfft 2D double-precision complex-to-complex transform using advanced interface
n: 4 5
howmany: 3
istride: 1      ostride: 1
inembed: 4 5
onembed: 4 5
idist: 20       odist: 20

input:
batch: 0
(0,0) (0,1) (0,2) (0,3) (0,4) 
(1,0) (1,1) (1,2) (1,3) (1,4) 
(2,0) (2,1) (2,2) (2,3) (2,4) 
(3,0) (3,1) (3,2) (3,3) (3,4) 

batch: 1
(1,0) (1,1) (1,2) (1,3) (1,4) 
(2,0) (2,1) (2,2) (2,3) (2,4) 
(3,0) (3,1) (3,2) (3,3) (3,4) 
(4,0) (4,1) (4,2) (4,3) (4,4) 

batch: 2
(2,0) (2,1) (2,2) (2,3) (2,4) 
(3,0) (3,1) (3,2) (3,3) (3,4) 
(4,0) (4,1) (4,2) (4,3) (4,4) 
(5,0) (5,1) (5,2) (5,3) (5,4) 


terminate called after throwing an instance of 'std::runtime_error'
  what():  Undefined __global__ function.
Aborted
$ ./hipfft_setworkarea
hipfft 1D single-precision real-to-complex transform showing work memory usage
hipFFT major_version 0
input:
0 1 2 3 4 5 6 7 8 
hipfftEstimate 1d workSize: 72
hipfftGetSize workSize: 72
terminate called after throwing an instance of 'std::runtime_error'
  what():  Undefined __global__ function.
Aborted
```

**Comment by malcolmroberts** [comment]
The Hawaii cards are enabled, but not officially supported; see https://rocm.github.io/hardware.html .  That said, if you change CMakeLists.txt and add gfx701 AMDGPU_TARGETS, you should probably be able to get it to compile, if you're comfortable with that.

**Comment by Lucretia** [comment]
I've already done that and got it to compile.

**Comment by skeelyamd** [comment]
At first glance this looks like a HIP issue.  It appears (from GDB trace and error messages) that something has gone wrong with either their compilation options or how they are looking up symbols.

HIP can be found here: https://github.com/ROCm-Developer-Tools/HIP

**Comment by skeelyamd** [comment]
Adding @gargrahul, from HIP team.

**Comment by Lucretia** [comment]
You can see how it's built [here](https://github.com/Lucretia/rocm/blob/add-gfx701-2.8.0/sci-libs/rocFFT/rocFFT-2.8.0.ebuild) and the [patch](https://github.com/Lucretia/rocm/blob/add-gfx701-2.8.0/sci-libs/rocFFT/files/0001-Add-gfx701-Hawaii.patch)

**Comment by ramcherukuri** [comment]
@Lucretia Can you try  -fno-gpu-rdc compiler option. Check this link for some info https://reviews.llvm.org/D52377

**Comment by Lucretia** [comment]
@ramcherukuri No, same exception.
